# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b4b7941d4a20001b97d319270d78e5e2c4586322d18ae4f9d1c50e3038817e5c8e056d297de98bba07aa44261cb426e89909dff650ced9701f2c54240b26843

test:
  secret_key_base: bd64f39b50accd0af105a58549248ba9b96c45b0cc08ce4e28b684c0c86322ebf05d3cf770ddfe9bea2abbf0b05b4dcf4410a170293d84a990abcae957a74ac9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
